### ISSUE TITLE
Wrong type hint

### ISSUE THREAD

**Issue by datajoely** [getindata/kedro-snowflake#10]
The `companies` dataframe is of type `sp.DataFrame` not pandas

https://github.com/getindata/kedro-snowflake/blob/b273ba2e4ba5470e9a8568d9f1b381bd3cf3df7c/kedro_snowflake/starters/snowflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/pipelines/data_processing/nodes.py#LL65C40-L65C50

**Comment by Lasica** [comment]
Thanks! Corrected in the upcoming 0.2.0 release.
