### ISSUE TITLE
make package compatible with python > 3.9

### ISSUE THREAD

**Issue by hugocool** [getindata/kedro-snowflake#9]
We're using python v3.9.10, and moving to 3.10 soon.
now i get the following error when trying to install `kedro-snowflake` with `poetry`:

```
poetry add kedro-snowflake
Using version ^0.1.2 for kedro-snowflake

Updating dependencies
Resolving dependencies... (0.1s)

The current project's Python requirement (>=3.9.10,<3.10) is not compatible with some of the required packages Python requirement:
  - kedro-snowflake requires Python >=3.8,<3.9, so it will not be satisfied for Python >=3.9.10,<3.10

Because no versions of kedro-snowflake match >0.1.2,<0.2.0
 and kedro-snowflake (0.1.2) requires Python >=3.8,<3.9, kedro-snowflake is forbidden.
So, because isco-classification depends on kedro-snowflake (^0.1.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For kedro-snowflake, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

Is `kedro-snowflake` incompatible with python 3.9+?
If not, we could simply adjust the python requirement in the `pyproject.toml`

**Comment by hugocool** [comment]
Okay, i made it work with Python 3.9+ by pulling the latest version of main from `snowflake-snowpark-python`.
So i updated the dependencies to:

```
[tool.poetry.dependencies]
python = ">=3.8,<3.10"
snowflake-snowpark-python = {git = "https://github.com/snowflakedb/snowpark-python.git", extras = ["pandas"], branch = "main" }
kedro-datasets = {version = ">=1", extras = ["pandas-csvdataset", "pandas-exceldataset", "pandas-parquetdataset", "snowflake-snowparktabledataset"]}
```

You will probably need to wait for the next release of `snowflake-snowpark-python`, and have a look at the `kedro-datasets` version which is required.

I haven't tested whether your package actually works now on python 3.9.10, but i know it installs.
ill report back once i pulled data from snowflake.

**Comment by marrrcin** [comment]
Hi @hugocool ! Thanks for the issue. As of 2023-06-05 I don't think that this package and it's dependency: `snowflake-snowpark-python` will work with Python 3.9.  In the latest official release of `snowflake-snowpark-python` ,the support for Python 3.9 is not there yet:
https://github.com/snowflakedb/snowpark-python/blob/1d6973e1ba03d27d8e64c4b2f856a4a70defb03c/setup.py#L14

Once the support for newer Python versions will be released by Snowflake, we will surely update this plugin's dependencies.

![8C439516-2402-4386-83F2-69900BEE05C4](https://github.com/getindata/kedro-snowflake/assets/6958772/07509ad2-2ac2-40a7-a65c-8a08213d96fc)
